### PR TITLE
New belt_neighbors logic for splitters/loaders

### PR DESCRIPTION
**Pull request by zero318**
Logic still needs to be revised for belts/undergrounds

### CODE REVIEW

**Comment by raiguard** [comment]
Referencing issue #2

**Comment by raiguard** [comment]
Could you please add me as a collaborator in your fork so I can directly contribute to the PR?

**Comment by zero318** [comment]
Added

**Comment by zero318** [comment]
Just updated the pull request to not conflict with the new loader copy/paste check.

Github seems to be properly comparing the files now too.

**Comment by raiguard** [comment]
Something screwy is still going on. It's saying you're replacing the entire file, even though you're not. Are you accidentally converting it to a different encoding or something?

**Comment by zero318** [comment]
Oh, it's probably because of how I made the commit.

I'd extracted the zipped mod and edited the script with Notepad++ then uploaded the edited file to the fork. Apparently Github didn't realize that I was just trying to update an existing file.

Resolving the merge conflict seems like it helped though. It's no longer saying that there are a thousand additions and deletions.

**Comment by raiguard** [comment]
Ah, so you didn't actually clone it, that makes sense. It doesn't really matter, it doesn't break anything. The only thing it hurts is my OCD.

**Comment by zero318** [comment]
Yeah, I haven't really used Github very much beyond basic version tracking, so I'm not very familiar with the nuances of the system. My bad. ^_^;

**Comment by raiguard** [comment]
Alright, it seems to be good. Ideally I would want to find a way to re-combine the snapping logic into one function, but that would take longer than it would be worth. Merging!

**Pull request merged**
